name: prepend_http
description: Prepend `https://` to humanized URLs.
version: 1.0.0
homepage: https://github.com/NarHakobyan/prepend_http
author: narek <narek.hakobyan.07@gmail.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
